# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hb/cpp_server_frame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hb/cpp_server_frame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hb/cpp_server_frame/CMakeFiles /home/hb/cpp_server_frame//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hb/cpp_server_frame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named aboo

# Build rule for target.
aboo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 aboo
.PHONY : aboo

# fast build rule for target.
aboo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/build
.PHONY : aboo/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_scheduler

# Build rule for target.
test_scheduler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_scheduler
.PHONY : test_scheduler

# fast build rule for target.
test_scheduler/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/build
.PHONY : test_scheduler/fast

#=============================================================================
# Target rules for targets named test_iomanager

# Build rule for target.
test_iomanager: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_iomanager
.PHONY : test_iomanager

# fast build rule for target.
test_iomanager/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/build
.PHONY : test_iomanager/fast

#=============================================================================
# Target rules for targets named test_hook

# Build rule for target.
test_hook: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_hook
.PHONY : test_hook

# fast build rule for target.
test_hook/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/build
.PHONY : test_hook/fast

#=============================================================================
# Target rules for targets named test_address

# Build rule for target.
test_address: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_address
.PHONY : test_address

# fast build rule for target.
test_address/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/build
.PHONY : test_address/fast

#=============================================================================
# Target rules for targets named test_socket

# Build rule for target.
test_socket: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_socket
.PHONY : test_socket

# fast build rule for target.
test_socket/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/build
.PHONY : test_socket/fast

#=============================================================================
# Target rules for targets named test_bytearray

# Build rule for target.
test_bytearray: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_bytearray
.PHONY : test_bytearray

# fast build rule for target.
test_bytearray/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/build
.PHONY : test_bytearray/fast

#=============================================================================
# Target rules for targets named test_http

# Build rule for target.
test_http: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_http
.PHONY : test_http

# fast build rule for target.
test_http/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/build
.PHONY : test_http/fast

#=============================================================================
# Target rules for targets named test_http_parser

# Build rule for target.
test_http_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_http_parser
.PHONY : test_http_parser

# fast build rule for target.
test_http_parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/build
.PHONY : test_http_parser/fast

#=============================================================================
# Target rules for targets named test_tcp_server

# Build rule for target.
test_tcp_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_tcp_server
.PHONY : test_tcp_server

# fast build rule for target.
test_tcp_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/build
.PHONY : test_tcp_server/fast

#=============================================================================
# Target rules for targets named echo_server

# Build rule for target.
echo_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 echo_server
.PHONY : echo_server

# fast build rule for target.
echo_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/build
.PHONY : echo_server/fast

#=============================================================================
# Target rules for targets named test_http_server

# Build rule for target.
test_http_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_http_server
.PHONY : test_http_server

# fast build rule for target.
test_http_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/build
.PHONY : test_http_server/fast

#=============================================================================
# Target rules for targets named test_http_connection

# Build rule for target.
test_http_connection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_http_connection
.PHONY : test_http_connection

# fast build rule for target.
test_http_connection/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/build
.PHONY : test_http_connection/fast

#=============================================================================
# Target rules for targets named test_uri

# Build rule for target.
test_uri: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_uri
.PHONY : test_uri

# fast build rule for target.
test_uri/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/build
.PHONY : test_uri/fast

aboo/address.o: aboo/address.cpp.o
.PHONY : aboo/address.o

# target to build an object file
aboo/address.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/address.cpp.o
.PHONY : aboo/address.cpp.o

aboo/address.i: aboo/address.cpp.i
.PHONY : aboo/address.i

# target to preprocess a source file
aboo/address.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/address.cpp.i
.PHONY : aboo/address.cpp.i

aboo/address.s: aboo/address.cpp.s
.PHONY : aboo/address.s

# target to generate assembly for a file
aboo/address.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/address.cpp.s
.PHONY : aboo/address.cpp.s

aboo/bytearray.o: aboo/bytearray.cpp.o
.PHONY : aboo/bytearray.o

# target to build an object file
aboo/bytearray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/bytearray.cpp.o
.PHONY : aboo/bytearray.cpp.o

aboo/bytearray.i: aboo/bytearray.cpp.i
.PHONY : aboo/bytearray.i

# target to preprocess a source file
aboo/bytearray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/bytearray.cpp.i
.PHONY : aboo/bytearray.cpp.i

aboo/bytearray.s: aboo/bytearray.cpp.s
.PHONY : aboo/bytearray.s

# target to generate assembly for a file
aboo/bytearray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/bytearray.cpp.s
.PHONY : aboo/bytearray.cpp.s

aboo/config.o: aboo/config.cpp.o
.PHONY : aboo/config.o

# target to build an object file
aboo/config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/config.cpp.o
.PHONY : aboo/config.cpp.o

aboo/config.i: aboo/config.cpp.i
.PHONY : aboo/config.i

# target to preprocess a source file
aboo/config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/config.cpp.i
.PHONY : aboo/config.cpp.i

aboo/config.s: aboo/config.cpp.s
.PHONY : aboo/config.s

# target to generate assembly for a file
aboo/config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/config.cpp.s
.PHONY : aboo/config.cpp.s

aboo/fd_manager.o: aboo/fd_manager.cpp.o
.PHONY : aboo/fd_manager.o

# target to build an object file
aboo/fd_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/fd_manager.cpp.o
.PHONY : aboo/fd_manager.cpp.o

aboo/fd_manager.i: aboo/fd_manager.cpp.i
.PHONY : aboo/fd_manager.i

# target to preprocess a source file
aboo/fd_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/fd_manager.cpp.i
.PHONY : aboo/fd_manager.cpp.i

aboo/fd_manager.s: aboo/fd_manager.cpp.s
.PHONY : aboo/fd_manager.s

# target to generate assembly for a file
aboo/fd_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/fd_manager.cpp.s
.PHONY : aboo/fd_manager.cpp.s

aboo/fiber.o: aboo/fiber.cpp.o
.PHONY : aboo/fiber.o

# target to build an object file
aboo/fiber.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/fiber.cpp.o
.PHONY : aboo/fiber.cpp.o

aboo/fiber.i: aboo/fiber.cpp.i
.PHONY : aboo/fiber.i

# target to preprocess a source file
aboo/fiber.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/fiber.cpp.i
.PHONY : aboo/fiber.cpp.i

aboo/fiber.s: aboo/fiber.cpp.s
.PHONY : aboo/fiber.s

# target to generate assembly for a file
aboo/fiber.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/fiber.cpp.s
.PHONY : aboo/fiber.cpp.s

aboo/hook.o: aboo/hook.cpp.o
.PHONY : aboo/hook.o

# target to build an object file
aboo/hook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/hook.cpp.o
.PHONY : aboo/hook.cpp.o

aboo/hook.i: aboo/hook.cpp.i
.PHONY : aboo/hook.i

# target to preprocess a source file
aboo/hook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/hook.cpp.i
.PHONY : aboo/hook.cpp.i

aboo/hook.s: aboo/hook.cpp.s
.PHONY : aboo/hook.s

# target to generate assembly for a file
aboo/hook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/hook.cpp.s
.PHONY : aboo/hook.cpp.s

aboo/http/http.o: aboo/http/http.cpp.o
.PHONY : aboo/http/http.o

# target to build an object file
aboo/http/http.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http.cpp.o
.PHONY : aboo/http/http.cpp.o

aboo/http/http.i: aboo/http/http.cpp.i
.PHONY : aboo/http/http.i

# target to preprocess a source file
aboo/http/http.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http.cpp.i
.PHONY : aboo/http/http.cpp.i

aboo/http/http.s: aboo/http/http.cpp.s
.PHONY : aboo/http/http.s

# target to generate assembly for a file
aboo/http/http.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http.cpp.s
.PHONY : aboo/http/http.cpp.s

aboo/http/http11_parser.rl.o: aboo/http/http11_parser.rl.cpp.o
.PHONY : aboo/http/http11_parser.rl.o

# target to build an object file
aboo/http/http11_parser.rl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http11_parser.rl.cpp.o
.PHONY : aboo/http/http11_parser.rl.cpp.o

aboo/http/http11_parser.rl.i: aboo/http/http11_parser.rl.cpp.i
.PHONY : aboo/http/http11_parser.rl.i

# target to preprocess a source file
aboo/http/http11_parser.rl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http11_parser.rl.cpp.i
.PHONY : aboo/http/http11_parser.rl.cpp.i

aboo/http/http11_parser.rl.s: aboo/http/http11_parser.rl.cpp.s
.PHONY : aboo/http/http11_parser.rl.s

# target to generate assembly for a file
aboo/http/http11_parser.rl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http11_parser.rl.cpp.s
.PHONY : aboo/http/http11_parser.rl.cpp.s

aboo/http/http_connection.o: aboo/http/http_connection.cpp.o
.PHONY : aboo/http/http_connection.o

# target to build an object file
aboo/http/http_connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_connection.cpp.o
.PHONY : aboo/http/http_connection.cpp.o

aboo/http/http_connection.i: aboo/http/http_connection.cpp.i
.PHONY : aboo/http/http_connection.i

# target to preprocess a source file
aboo/http/http_connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_connection.cpp.i
.PHONY : aboo/http/http_connection.cpp.i

aboo/http/http_connection.s: aboo/http/http_connection.cpp.s
.PHONY : aboo/http/http_connection.s

# target to generate assembly for a file
aboo/http/http_connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_connection.cpp.s
.PHONY : aboo/http/http_connection.cpp.s

aboo/http/http_parser.o: aboo/http/http_parser.cpp.o
.PHONY : aboo/http/http_parser.o

# target to build an object file
aboo/http/http_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_parser.cpp.o
.PHONY : aboo/http/http_parser.cpp.o

aboo/http/http_parser.i: aboo/http/http_parser.cpp.i
.PHONY : aboo/http/http_parser.i

# target to preprocess a source file
aboo/http/http_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_parser.cpp.i
.PHONY : aboo/http/http_parser.cpp.i

aboo/http/http_parser.s: aboo/http/http_parser.cpp.s
.PHONY : aboo/http/http_parser.s

# target to generate assembly for a file
aboo/http/http_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_parser.cpp.s
.PHONY : aboo/http/http_parser.cpp.s

aboo/http/http_server.o: aboo/http/http_server.cpp.o
.PHONY : aboo/http/http_server.o

# target to build an object file
aboo/http/http_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_server.cpp.o
.PHONY : aboo/http/http_server.cpp.o

aboo/http/http_server.i: aboo/http/http_server.cpp.i
.PHONY : aboo/http/http_server.i

# target to preprocess a source file
aboo/http/http_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_server.cpp.i
.PHONY : aboo/http/http_server.cpp.i

aboo/http/http_server.s: aboo/http/http_server.cpp.s
.PHONY : aboo/http/http_server.s

# target to generate assembly for a file
aboo/http/http_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_server.cpp.s
.PHONY : aboo/http/http_server.cpp.s

aboo/http/http_session.o: aboo/http/http_session.cpp.o
.PHONY : aboo/http/http_session.o

# target to build an object file
aboo/http/http_session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_session.cpp.o
.PHONY : aboo/http/http_session.cpp.o

aboo/http/http_session.i: aboo/http/http_session.cpp.i
.PHONY : aboo/http/http_session.i

# target to preprocess a source file
aboo/http/http_session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_session.cpp.i
.PHONY : aboo/http/http_session.cpp.i

aboo/http/http_session.s: aboo/http/http_session.cpp.s
.PHONY : aboo/http/http_session.s

# target to generate assembly for a file
aboo/http/http_session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/http_session.cpp.s
.PHONY : aboo/http/http_session.cpp.s

aboo/http/httpclient_parser.rl.o: aboo/http/httpclient_parser.rl.cpp.o
.PHONY : aboo/http/httpclient_parser.rl.o

# target to build an object file
aboo/http/httpclient_parser.rl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/httpclient_parser.rl.cpp.o
.PHONY : aboo/http/httpclient_parser.rl.cpp.o

aboo/http/httpclient_parser.rl.i: aboo/http/httpclient_parser.rl.cpp.i
.PHONY : aboo/http/httpclient_parser.rl.i

# target to preprocess a source file
aboo/http/httpclient_parser.rl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/httpclient_parser.rl.cpp.i
.PHONY : aboo/http/httpclient_parser.rl.cpp.i

aboo/http/httpclient_parser.rl.s: aboo/http/httpclient_parser.rl.cpp.s
.PHONY : aboo/http/httpclient_parser.rl.s

# target to generate assembly for a file
aboo/http/httpclient_parser.rl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/httpclient_parser.rl.cpp.s
.PHONY : aboo/http/httpclient_parser.rl.cpp.s

aboo/http/servlet.o: aboo/http/servlet.cpp.o
.PHONY : aboo/http/servlet.o

# target to build an object file
aboo/http/servlet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/servlet.cpp.o
.PHONY : aboo/http/servlet.cpp.o

aboo/http/servlet.i: aboo/http/servlet.cpp.i
.PHONY : aboo/http/servlet.i

# target to preprocess a source file
aboo/http/servlet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/servlet.cpp.i
.PHONY : aboo/http/servlet.cpp.i

aboo/http/servlet.s: aboo/http/servlet.cpp.s
.PHONY : aboo/http/servlet.s

# target to generate assembly for a file
aboo/http/servlet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/http/servlet.cpp.s
.PHONY : aboo/http/servlet.cpp.s

aboo/iomanager.o: aboo/iomanager.cpp.o
.PHONY : aboo/iomanager.o

# target to build an object file
aboo/iomanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/iomanager.cpp.o
.PHONY : aboo/iomanager.cpp.o

aboo/iomanager.i: aboo/iomanager.cpp.i
.PHONY : aboo/iomanager.i

# target to preprocess a source file
aboo/iomanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/iomanager.cpp.i
.PHONY : aboo/iomanager.cpp.i

aboo/iomanager.s: aboo/iomanager.cpp.s
.PHONY : aboo/iomanager.s

# target to generate assembly for a file
aboo/iomanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/iomanager.cpp.s
.PHONY : aboo/iomanager.cpp.s

aboo/log.o: aboo/log.cpp.o
.PHONY : aboo/log.o

# target to build an object file
aboo/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/log.cpp.o
.PHONY : aboo/log.cpp.o

aboo/log.i: aboo/log.cpp.i
.PHONY : aboo/log.i

# target to preprocess a source file
aboo/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/log.cpp.i
.PHONY : aboo/log.cpp.i

aboo/log.s: aboo/log.cpp.s
.PHONY : aboo/log.s

# target to generate assembly for a file
aboo/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/log.cpp.s
.PHONY : aboo/log.cpp.s

aboo/scheduler.o: aboo/scheduler.cpp.o
.PHONY : aboo/scheduler.o

# target to build an object file
aboo/scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/scheduler.cpp.o
.PHONY : aboo/scheduler.cpp.o

aboo/scheduler.i: aboo/scheduler.cpp.i
.PHONY : aboo/scheduler.i

# target to preprocess a source file
aboo/scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/scheduler.cpp.i
.PHONY : aboo/scheduler.cpp.i

aboo/scheduler.s: aboo/scheduler.cpp.s
.PHONY : aboo/scheduler.s

# target to generate assembly for a file
aboo/scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/scheduler.cpp.s
.PHONY : aboo/scheduler.cpp.s

aboo/socket.o: aboo/socket.cpp.o
.PHONY : aboo/socket.o

# target to build an object file
aboo/socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/socket.cpp.o
.PHONY : aboo/socket.cpp.o

aboo/socket.i: aboo/socket.cpp.i
.PHONY : aboo/socket.i

# target to preprocess a source file
aboo/socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/socket.cpp.i
.PHONY : aboo/socket.cpp.i

aboo/socket.s: aboo/socket.cpp.s
.PHONY : aboo/socket.s

# target to generate assembly for a file
aboo/socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/socket.cpp.s
.PHONY : aboo/socket.cpp.s

aboo/socket_stream.o: aboo/socket_stream.cpp.o
.PHONY : aboo/socket_stream.o

# target to build an object file
aboo/socket_stream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/socket_stream.cpp.o
.PHONY : aboo/socket_stream.cpp.o

aboo/socket_stream.i: aboo/socket_stream.cpp.i
.PHONY : aboo/socket_stream.i

# target to preprocess a source file
aboo/socket_stream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/socket_stream.cpp.i
.PHONY : aboo/socket_stream.cpp.i

aboo/socket_stream.s: aboo/socket_stream.cpp.s
.PHONY : aboo/socket_stream.s

# target to generate assembly for a file
aboo/socket_stream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/socket_stream.cpp.s
.PHONY : aboo/socket_stream.cpp.s

aboo/stream.o: aboo/stream.cpp.o
.PHONY : aboo/stream.o

# target to build an object file
aboo/stream.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/stream.cpp.o
.PHONY : aboo/stream.cpp.o

aboo/stream.i: aboo/stream.cpp.i
.PHONY : aboo/stream.i

# target to preprocess a source file
aboo/stream.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/stream.cpp.i
.PHONY : aboo/stream.cpp.i

aboo/stream.s: aboo/stream.cpp.s
.PHONY : aboo/stream.s

# target to generate assembly for a file
aboo/stream.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/stream.cpp.s
.PHONY : aboo/stream.cpp.s

aboo/tcp_server.o: aboo/tcp_server.cpp.o
.PHONY : aboo/tcp_server.o

# target to build an object file
aboo/tcp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/tcp_server.cpp.o
.PHONY : aboo/tcp_server.cpp.o

aboo/tcp_server.i: aboo/tcp_server.cpp.i
.PHONY : aboo/tcp_server.i

# target to preprocess a source file
aboo/tcp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/tcp_server.cpp.i
.PHONY : aboo/tcp_server.cpp.i

aboo/tcp_server.s: aboo/tcp_server.cpp.s
.PHONY : aboo/tcp_server.s

# target to generate assembly for a file
aboo/tcp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/tcp_server.cpp.s
.PHONY : aboo/tcp_server.cpp.s

aboo/thread.o: aboo/thread.cpp.o
.PHONY : aboo/thread.o

# target to build an object file
aboo/thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/thread.cpp.o
.PHONY : aboo/thread.cpp.o

aboo/thread.i: aboo/thread.cpp.i
.PHONY : aboo/thread.i

# target to preprocess a source file
aboo/thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/thread.cpp.i
.PHONY : aboo/thread.cpp.i

aboo/thread.s: aboo/thread.cpp.s
.PHONY : aboo/thread.s

# target to generate assembly for a file
aboo/thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/thread.cpp.s
.PHONY : aboo/thread.cpp.s

aboo/timer.o: aboo/timer.cpp.o
.PHONY : aboo/timer.o

# target to build an object file
aboo/timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/timer.cpp.o
.PHONY : aboo/timer.cpp.o

aboo/timer.i: aboo/timer.cpp.i
.PHONY : aboo/timer.i

# target to preprocess a source file
aboo/timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/timer.cpp.i
.PHONY : aboo/timer.cpp.i

aboo/timer.s: aboo/timer.cpp.s
.PHONY : aboo/timer.s

# target to generate assembly for a file
aboo/timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/timer.cpp.s
.PHONY : aboo/timer.cpp.s

aboo/uri.rl.o: aboo/uri.rl.cpp.o
.PHONY : aboo/uri.rl.o

# target to build an object file
aboo/uri.rl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/uri.rl.cpp.o
.PHONY : aboo/uri.rl.cpp.o

aboo/uri.rl.i: aboo/uri.rl.cpp.i
.PHONY : aboo/uri.rl.i

# target to preprocess a source file
aboo/uri.rl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/uri.rl.cpp.i
.PHONY : aboo/uri.rl.cpp.i

aboo/uri.rl.s: aboo/uri.rl.cpp.s
.PHONY : aboo/uri.rl.s

# target to generate assembly for a file
aboo/uri.rl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/uri.rl.cpp.s
.PHONY : aboo/uri.rl.cpp.s

aboo/util.o: aboo/util.cpp.o
.PHONY : aboo/util.o

# target to build an object file
aboo/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/util.cpp.o
.PHONY : aboo/util.cpp.o

aboo/util.i: aboo/util.cpp.i
.PHONY : aboo/util.i

# target to preprocess a source file
aboo/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/util.cpp.i
.PHONY : aboo/util.cpp.i

aboo/util.s: aboo/util.cpp.s
.PHONY : aboo/util.s

# target to generate assembly for a file
aboo/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/aboo.dir/build.make CMakeFiles/aboo.dir/aboo/util.cpp.s
.PHONY : aboo/util.cpp.s

examples/echo_server.o: examples/echo_server.cpp.o
.PHONY : examples/echo_server.o

# target to build an object file
examples/echo_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cpp.o
.PHONY : examples/echo_server.cpp.o

examples/echo_server.i: examples/echo_server.cpp.i
.PHONY : examples/echo_server.i

# target to preprocess a source file
examples/echo_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cpp.i
.PHONY : examples/echo_server.cpp.i

examples/echo_server.s: examples/echo_server.cpp.s
.PHONY : examples/echo_server.s

# target to generate assembly for a file
examples/echo_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/echo_server.dir/build.make CMakeFiles/echo_server.dir/examples/echo_server.cpp.s
.PHONY : examples/echo_server.cpp.s

tests/test.o: tests/test.cpp.o
.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i
.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s
.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

tests/test_address.o: tests/test_address.cpp.o
.PHONY : tests/test_address.o

# target to build an object file
tests/test_address.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cpp.o
.PHONY : tests/test_address.cpp.o

tests/test_address.i: tests/test_address.cpp.i
.PHONY : tests/test_address.i

# target to preprocess a source file
tests/test_address.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cpp.i
.PHONY : tests/test_address.cpp.i

tests/test_address.s: tests/test_address.cpp.s
.PHONY : tests/test_address.s

# target to generate assembly for a file
tests/test_address.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_address.dir/build.make CMakeFiles/test_address.dir/tests/test_address.cpp.s
.PHONY : tests/test_address.cpp.s

tests/test_bytearray.o: tests/test_bytearray.cpp.o
.PHONY : tests/test_bytearray.o

# target to build an object file
tests/test_bytearray.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cpp.o
.PHONY : tests/test_bytearray.cpp.o

tests/test_bytearray.i: tests/test_bytearray.cpp.i
.PHONY : tests/test_bytearray.i

# target to preprocess a source file
tests/test_bytearray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cpp.i
.PHONY : tests/test_bytearray.cpp.i

tests/test_bytearray.s: tests/test_bytearray.cpp.s
.PHONY : tests/test_bytearray.s

# target to generate assembly for a file
tests/test_bytearray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_bytearray.dir/build.make CMakeFiles/test_bytearray.dir/tests/test_bytearray.cpp.s
.PHONY : tests/test_bytearray.cpp.s

tests/test_config.o: tests/test_config.cpp.o
.PHONY : tests/test_config.o

# target to build an object file
tests/test_config.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.o
.PHONY : tests/test_config.cpp.o

tests/test_config.i: tests/test_config.cpp.i
.PHONY : tests/test_config.i

# target to preprocess a source file
tests/test_config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.i
.PHONY : tests/test_config.cpp.i

tests/test_config.s: tests/test_config.cpp.s
.PHONY : tests/test_config.s

# target to generate assembly for a file
tests/test_config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/tests/test_config.cpp.s
.PHONY : tests/test_config.cpp.s

tests/test_fiber.o: tests/test_fiber.cpp.o
.PHONY : tests/test_fiber.o

# target to build an object file
tests/test_fiber.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.o
.PHONY : tests/test_fiber.cpp.o

tests/test_fiber.i: tests/test_fiber.cpp.i
.PHONY : tests/test_fiber.i

# target to preprocess a source file
tests/test_fiber.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.i
.PHONY : tests/test_fiber.cpp.i

tests/test_fiber.s: tests/test_fiber.cpp.s
.PHONY : tests/test_fiber.s

# target to generate assembly for a file
tests/test_fiber.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/tests/test_fiber.cpp.s
.PHONY : tests/test_fiber.cpp.s

tests/test_hook.o: tests/test_hook.cpp.o
.PHONY : tests/test_hook.o

# target to build an object file
tests/test_hook.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.o
.PHONY : tests/test_hook.cpp.o

tests/test_hook.i: tests/test_hook.cpp.i
.PHONY : tests/test_hook.i

# target to preprocess a source file
tests/test_hook.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.i
.PHONY : tests/test_hook.cpp.i

tests/test_hook.s: tests/test_hook.cpp.s
.PHONY : tests/test_hook.s

# target to generate assembly for a file
tests/test_hook.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_hook.dir/build.make CMakeFiles/test_hook.dir/tests/test_hook.cpp.s
.PHONY : tests/test_hook.cpp.s

tests/test_http.o: tests/test_http.cpp.o
.PHONY : tests/test_http.o

# target to build an object file
tests/test_http.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cpp.o
.PHONY : tests/test_http.cpp.o

tests/test_http.i: tests/test_http.cpp.i
.PHONY : tests/test_http.i

# target to preprocess a source file
tests/test_http.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cpp.i
.PHONY : tests/test_http.cpp.i

tests/test_http.s: tests/test_http.cpp.s
.PHONY : tests/test_http.s

# target to generate assembly for a file
tests/test_http.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http.dir/build.make CMakeFiles/test_http.dir/tests/test_http.cpp.s
.PHONY : tests/test_http.cpp.s

tests/test_http_connection.o: tests/test_http_connection.cpp.o
.PHONY : tests/test_http_connection.o

# target to build an object file
tests/test_http_connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.o
.PHONY : tests/test_http_connection.cpp.o

tests/test_http_connection.i: tests/test_http_connection.cpp.i
.PHONY : tests/test_http_connection.i

# target to preprocess a source file
tests/test_http_connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.i
.PHONY : tests/test_http_connection.cpp.i

tests/test_http_connection.s: tests/test_http_connection.cpp.s
.PHONY : tests/test_http_connection.s

# target to generate assembly for a file
tests/test_http_connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_connection.dir/build.make CMakeFiles/test_http_connection.dir/tests/test_http_connection.cpp.s
.PHONY : tests/test_http_connection.cpp.s

tests/test_http_parser.o: tests/test_http_parser.cpp.o
.PHONY : tests/test_http_parser.o

# target to build an object file
tests/test_http_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.o
.PHONY : tests/test_http_parser.cpp.o

tests/test_http_parser.i: tests/test_http_parser.cpp.i
.PHONY : tests/test_http_parser.i

# target to preprocess a source file
tests/test_http_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.i
.PHONY : tests/test_http_parser.cpp.i

tests/test_http_parser.s: tests/test_http_parser.cpp.s
.PHONY : tests/test_http_parser.s

# target to generate assembly for a file
tests/test_http_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_parser.dir/build.make CMakeFiles/test_http_parser.dir/tests/test_http_parser.cpp.s
.PHONY : tests/test_http_parser.cpp.s

tests/test_http_server.o: tests/test_http_server.cpp.o
.PHONY : tests/test_http_server.o

# target to build an object file
tests/test_http_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cpp.o
.PHONY : tests/test_http_server.cpp.o

tests/test_http_server.i: tests/test_http_server.cpp.i
.PHONY : tests/test_http_server.i

# target to preprocess a source file
tests/test_http_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cpp.i
.PHONY : tests/test_http_server.cpp.i

tests/test_http_server.s: tests/test_http_server.cpp.s
.PHONY : tests/test_http_server.s

# target to generate assembly for a file
tests/test_http_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_http_server.dir/build.make CMakeFiles/test_http_server.dir/tests/test_http_server.cpp.s
.PHONY : tests/test_http_server.cpp.s

tests/test_iomanager.o: tests/test_iomanager.cpp.o
.PHONY : tests/test_iomanager.o

# target to build an object file
tests/test_iomanager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.o
.PHONY : tests/test_iomanager.cpp.o

tests/test_iomanager.i: tests/test_iomanager.cpp.i
.PHONY : tests/test_iomanager.i

# target to preprocess a source file
tests/test_iomanager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.i
.PHONY : tests/test_iomanager.cpp.i

tests/test_iomanager.s: tests/test_iomanager.cpp.s
.PHONY : tests/test_iomanager.s

# target to generate assembly for a file
tests/test_iomanager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_iomanager.dir/build.make CMakeFiles/test_iomanager.dir/tests/test_iomanager.cpp.s
.PHONY : tests/test_iomanager.cpp.s

tests/test_scheduler.o: tests/test_scheduler.cpp.o
.PHONY : tests/test_scheduler.o

# target to build an object file
tests/test_scheduler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.o
.PHONY : tests/test_scheduler.cpp.o

tests/test_scheduler.i: tests/test_scheduler.cpp.i
.PHONY : tests/test_scheduler.i

# target to preprocess a source file
tests/test_scheduler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.i
.PHONY : tests/test_scheduler.cpp.i

tests/test_scheduler.s: tests/test_scheduler.cpp.s
.PHONY : tests/test_scheduler.s

# target to generate assembly for a file
tests/test_scheduler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_scheduler.dir/build.make CMakeFiles/test_scheduler.dir/tests/test_scheduler.cpp.s
.PHONY : tests/test_scheduler.cpp.s

tests/test_socket.o: tests/test_socket.cpp.o
.PHONY : tests/test_socket.o

# target to build an object file
tests/test_socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.o
.PHONY : tests/test_socket.cpp.o

tests/test_socket.i: tests/test_socket.cpp.i
.PHONY : tests/test_socket.i

# target to preprocess a source file
tests/test_socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.i
.PHONY : tests/test_socket.cpp.i

tests/test_socket.s: tests/test_socket.cpp.s
.PHONY : tests/test_socket.s

# target to generate assembly for a file
tests/test_socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_socket.dir/build.make CMakeFiles/test_socket.dir/tests/test_socket.cpp.s
.PHONY : tests/test_socket.cpp.s

tests/test_tcp_server.o: tests/test_tcp_server.cpp.o
.PHONY : tests/test_tcp_server.o

# target to build an object file
tests/test_tcp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cpp.o
.PHONY : tests/test_tcp_server.cpp.o

tests/test_tcp_server.i: tests/test_tcp_server.cpp.i
.PHONY : tests/test_tcp_server.i

# target to preprocess a source file
tests/test_tcp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cpp.i
.PHONY : tests/test_tcp_server.cpp.i

tests/test_tcp_server.s: tests/test_tcp_server.cpp.s
.PHONY : tests/test_tcp_server.s

# target to generate assembly for a file
tests/test_tcp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_tcp_server.dir/build.make CMakeFiles/test_tcp_server.dir/tests/test_tcp_server.cpp.s
.PHONY : tests/test_tcp_server.cpp.s

tests/test_thread.o: tests/test_thread.cpp.o
.PHONY : tests/test_thread.o

# target to build an object file
tests/test_thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.o
.PHONY : tests/test_thread.cpp.o

tests/test_thread.i: tests/test_thread.cpp.i
.PHONY : tests/test_thread.i

# target to preprocess a source file
tests/test_thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.i
.PHONY : tests/test_thread.cpp.i

tests/test_thread.s: tests/test_thread.cpp.s
.PHONY : tests/test_thread.s

# target to generate assembly for a file
tests/test_thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/tests/test_thread.cpp.s
.PHONY : tests/test_thread.cpp.s

tests/test_uri.o: tests/test_uri.cpp.o
.PHONY : tests/test_uri.o

# target to build an object file
tests/test_uri.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cpp.o
.PHONY : tests/test_uri.cpp.o

tests/test_uri.i: tests/test_uri.cpp.i
.PHONY : tests/test_uri.i

# target to preprocess a source file
tests/test_uri.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cpp.i
.PHONY : tests/test_uri.cpp.i

tests/test_uri.s: tests/test_uri.cpp.s
.PHONY : tests/test_uri.s

# target to generate assembly for a file
tests/test_uri.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_uri.dir/build.make CMakeFiles/test_uri.dir/tests/test_uri.cpp.s
.PHONY : tests/test_uri.cpp.s

tests/test_util.o: tests/test_util.cpp.o
.PHONY : tests/test_util.o

# target to build an object file
tests/test_util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cpp.o
.PHONY : tests/test_util.cpp.o

tests/test_util.i: tests/test_util.cpp.i
.PHONY : tests/test_util.i

# target to preprocess a source file
tests/test_util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cpp.i
.PHONY : tests/test_util.cpp.i

tests/test_util.s: tests/test_util.cpp.s
.PHONY : tests/test_util.s

# target to generate assembly for a file
tests/test_util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/tests/test_util.cpp.s
.PHONY : tests/test_util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... aboo"
	@echo "... echo_server"
	@echo "... test"
	@echo "... test_address"
	@echo "... test_bytearray"
	@echo "... test_config"
	@echo "... test_fiber"
	@echo "... test_hook"
	@echo "... test_http"
	@echo "... test_http_connection"
	@echo "... test_http_parser"
	@echo "... test_http_server"
	@echo "... test_iomanager"
	@echo "... test_scheduler"
	@echo "... test_socket"
	@echo "... test_tcp_server"
	@echo "... test_thread"
	@echo "... test_uri"
	@echo "... test_util"
	@echo "... aboo/address.o"
	@echo "... aboo/address.i"
	@echo "... aboo/address.s"
	@echo "... aboo/bytearray.o"
	@echo "... aboo/bytearray.i"
	@echo "... aboo/bytearray.s"
	@echo "... aboo/config.o"
	@echo "... aboo/config.i"
	@echo "... aboo/config.s"
	@echo "... aboo/fd_manager.o"
	@echo "... aboo/fd_manager.i"
	@echo "... aboo/fd_manager.s"
	@echo "... aboo/fiber.o"
	@echo "... aboo/fiber.i"
	@echo "... aboo/fiber.s"
	@echo "... aboo/hook.o"
	@echo "... aboo/hook.i"
	@echo "... aboo/hook.s"
	@echo "... aboo/http/http.o"
	@echo "... aboo/http/http.i"
	@echo "... aboo/http/http.s"
	@echo "... aboo/http/http11_parser.rl.o"
	@echo "... aboo/http/http11_parser.rl.i"
	@echo "... aboo/http/http11_parser.rl.s"
	@echo "... aboo/http/http_connection.o"
	@echo "... aboo/http/http_connection.i"
	@echo "... aboo/http/http_connection.s"
	@echo "... aboo/http/http_parser.o"
	@echo "... aboo/http/http_parser.i"
	@echo "... aboo/http/http_parser.s"
	@echo "... aboo/http/http_server.o"
	@echo "... aboo/http/http_server.i"
	@echo "... aboo/http/http_server.s"
	@echo "... aboo/http/http_session.o"
	@echo "... aboo/http/http_session.i"
	@echo "... aboo/http/http_session.s"
	@echo "... aboo/http/httpclient_parser.rl.o"
	@echo "... aboo/http/httpclient_parser.rl.i"
	@echo "... aboo/http/httpclient_parser.rl.s"
	@echo "... aboo/http/servlet.o"
	@echo "... aboo/http/servlet.i"
	@echo "... aboo/http/servlet.s"
	@echo "... aboo/iomanager.o"
	@echo "... aboo/iomanager.i"
	@echo "... aboo/iomanager.s"
	@echo "... aboo/log.o"
	@echo "... aboo/log.i"
	@echo "... aboo/log.s"
	@echo "... aboo/scheduler.o"
	@echo "... aboo/scheduler.i"
	@echo "... aboo/scheduler.s"
	@echo "... aboo/socket.o"
	@echo "... aboo/socket.i"
	@echo "... aboo/socket.s"
	@echo "... aboo/socket_stream.o"
	@echo "... aboo/socket_stream.i"
	@echo "... aboo/socket_stream.s"
	@echo "... aboo/stream.o"
	@echo "... aboo/stream.i"
	@echo "... aboo/stream.s"
	@echo "... aboo/tcp_server.o"
	@echo "... aboo/tcp_server.i"
	@echo "... aboo/tcp_server.s"
	@echo "... aboo/thread.o"
	@echo "... aboo/thread.i"
	@echo "... aboo/thread.s"
	@echo "... aboo/timer.o"
	@echo "... aboo/timer.i"
	@echo "... aboo/timer.s"
	@echo "... aboo/uri.rl.o"
	@echo "... aboo/uri.rl.i"
	@echo "... aboo/uri.rl.s"
	@echo "... aboo/util.o"
	@echo "... aboo/util.i"
	@echo "... aboo/util.s"
	@echo "... examples/echo_server.o"
	@echo "... examples/echo_server.i"
	@echo "... examples/echo_server.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
	@echo "... tests/test_address.o"
	@echo "... tests/test_address.i"
	@echo "... tests/test_address.s"
	@echo "... tests/test_bytearray.o"
	@echo "... tests/test_bytearray.i"
	@echo "... tests/test_bytearray.s"
	@echo "... tests/test_config.o"
	@echo "... tests/test_config.i"
	@echo "... tests/test_config.s"
	@echo "... tests/test_fiber.o"
	@echo "... tests/test_fiber.i"
	@echo "... tests/test_fiber.s"
	@echo "... tests/test_hook.o"
	@echo "... tests/test_hook.i"
	@echo "... tests/test_hook.s"
	@echo "... tests/test_http.o"
	@echo "... tests/test_http.i"
	@echo "... tests/test_http.s"
	@echo "... tests/test_http_connection.o"
	@echo "... tests/test_http_connection.i"
	@echo "... tests/test_http_connection.s"
	@echo "... tests/test_http_parser.o"
	@echo "... tests/test_http_parser.i"
	@echo "... tests/test_http_parser.s"
	@echo "... tests/test_http_server.o"
	@echo "... tests/test_http_server.i"
	@echo "... tests/test_http_server.s"
	@echo "... tests/test_iomanager.o"
	@echo "... tests/test_iomanager.i"
	@echo "... tests/test_iomanager.s"
	@echo "... tests/test_scheduler.o"
	@echo "... tests/test_scheduler.i"
	@echo "... tests/test_scheduler.s"
	@echo "... tests/test_socket.o"
	@echo "... tests/test_socket.i"
	@echo "... tests/test_socket.s"
	@echo "... tests/test_tcp_server.o"
	@echo "... tests/test_tcp_server.i"
	@echo "... tests/test_tcp_server.s"
	@echo "... tests/test_thread.o"
	@echo "... tests/test_thread.i"
	@echo "... tests/test_thread.s"
	@echo "... tests/test_uri.o"
	@echo "... tests/test_uri.i"
	@echo "... tests/test_uri.s"
	@echo "... tests/test_util.o"
	@echo "... tests/test_util.i"
	@echo "... tests/test_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

